// Regenerates the embedded copy of public/images/mandala.svg used as
// --mandala-bg in app/styles/tokens.css. Run after editing the SVG:
//
//   node scripts/inline-mandala.mjs
//
// Why embedded: on phones the mandala-painted page area is the page's
// "largest contentful paint", and as a url() it could only start
// downloading after the CSS had — a data URI arrives with the CSS.
import { readFile, writeFile } from "node:fs/promises";

const svg = (await readFile("public/images/mandala.svg", "utf8"))
  .replace(/<!--[\s\S]*?-->/g, "")
  .replace(/>\s+</g, "><")
  .replace(/\s+/g, " ")
  .trim();

// minimal percent-encoding for an SVG data URI inside url("…")
const encoded = svg
  .replace(/"/g, "'")
  .replace(/%/g, "%25")
  .replace(/#/g, "%23")
  .replace(/</g, "%3C")
  .replace(/>/g, "%3E");

const line = `  --mandala-bg: url("data:image/svg+xml,${encoded}");`;
const tokens = "app/styles/tokens.css";
const css = await readFile(tokens, "utf8");
const START = "  /* mandala watermark (generated by scripts/inline-mandala.mjs) */";

const next = css.includes(START)
  ? css.replace(new RegExp(`${START.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&")}\\n.*\\n`), `${START}\n${line}\n`)
  : css.replace(":root {\n", `:root {\n${START}\n${line}\n\n`);

await writeFile(tokens, next);
console.log(`--mandala-bg: ${encoded.length} chars`);
